import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theming/theme-provider'
import { ThemeSwitcher } from '@/components/theming/theme-switcher'
import { ThemeSwitcherPositioner } from '@/components/theming/theme-switcher-positioner'
import { JavaScriptDisabledNotification } from '@/components/java-script-disabled-notification'

export const dynamic = 'force-dynamic'

const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <JavaScriptDisabledNotification />
          <ThemeSwitcherPositioner>
            <ThemeSwitcher />
          </ThemeSwitcherPositioner>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
